import * as dotenv from 'dotenv-safe';

dotenv.config();

const {
  CLIENT_ID,
  DATABASE_URL,
  COOKIE_PWD,
  SALT,
  KAFKA_URL,
  COMUNDA_PASSWORD,
  COMUNDA_URL,
  COMUNDA_USER,
  DEFAULT_USER_EMAIL,
  DEFAULT_USER_PASSWORD,
  ENVIRONMENT_SLUG,
} = process.env;

export {
  CLIENT_ID,
  DATABASE_URL,
  COOKIE_PWD,
  SALT,
  KAFKA_URL,
  COMUNDA_PASSWORD,
  COMUNDA_URL,
  COMUNDA_USER,
  DEFAULT_USER_EMAIL,
  DEFAULT_USER_PASSWORD,
  ENVIRONMENT_SLUG,
};
